const data = [
  {
    id: "recZkNf2kwmdBcqd0",
    name: "White Hoodie with black",
    price: 50,
    image: "https://cdn.discordapp.com/attachments/999453454026158170/1172907876164055152/product1.jpg?ex=65620695&is=654f9195&hm=165ded8fb54b731ecf8e600fcb9485f5910b15df6366c39f997c3efb5524f7ee&",
    company: "RareMotions",
    description:
      "White hoodie with black design",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recEHmzvupvT8ZONH",
    name: "Black Hoodie",
    price: 60,
    image: "https://cdn.discordapp.com/attachments/999453454026158170/1172907876587687996/product2.jpg?ex=65620695&is=654f9195&hm=b0b3f7108a95cdc9a8cab99e5962a0e47a5c3ead99cd3a2d80a9145e15e97a16&",
    company: "RareMotions",
    description:
      "black hoodie with white design",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 6,
  },
  {
    id: "rec5NBwZ5zCD9nfF0",
    name: "Pink Hoodie",
    price: 50,
    image: "https://cdn.discordapp.com/attachments/999453454026158170/1172907876956782682/product3.jpg?ex=65620695&is=654f9195&hm=02a5a2343aa350b065578ddbd17951b5a13b13e8a19fd6e922703796dfb827af&",
    company: "RareMotions",
    description:
      "Pink hoodie with black design",
    category: "Casual",
    amount: 1,
    stock: 4,
  },
  {
    id: "recd1jIVIEChmiwhe",
    name: "White with red",
    price: 60,
    image: "https://cdn.discordapp.com/attachments/999453454026158170/1172907875660746803/product4.jpg?ex=65620695&is=654f9195&hm=93b280ef6f626be88620d58227a4bd7d1e258f54b4cea2e9f5798bd8e58c1609&",
    company: "RareMotions",
    description:
      "White hoodie with red design",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  /*{
    id: "recoM2MyHJGHLVi5l",
    name: "Striped Sweater",
    price: 80,
    image: "https://i.ibb.co/KmSkMbH/striped-sweater.png",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recotY5Nh00DQFdkm",
    name: "Yellow Trouser",
    price: 20,
    image: "https://i.ibb.co/v1cvwNf/yellow-track-suit.png",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "rec1Ntk7siEEW9ha1",
    name: "White Top",
    price: 40,
    image: "https://i.ibb.co/qBcrsJg/white-vest.png",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    shipping: true,
    amount: 1,
    stock: 2,
  },
  {
    id: "recNZ0koOqEmilmoz",
    name: "Pink Sweatshirt",
    price: 90,
    image: "https://i.ibb.co/ypkgK0X/blue-beanie.png",
    company: "Levis",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 3,
  },
  {
    id: "recrfxv3EwpvJwvjq",
    name: "Brown Coat",
    price: 100,
    image: "https://i.ibb.co/M6hHc3F/brown-trench.png",
    company: "Only",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Office",
    shipping: true,
    amount: 1,
    stock: 4,
  },
  {
    id: "recoW8ecgjtKx2Sj2",
    name: "Grey Jacket",
    price: 20,
    image: "https://i.ibb.co/N71k1ML/grey-jean-jacket.png",
    company: "Vero Moda",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis, provident. Itaque totam neque, nesciunt consequatur error quasi ipsam accusamus facere!Lorem ipsum dolor sit amet consectetur adipisicing elit.",
    category: "Casual",
    amount: 1,
    stock: 5,
  },*/
];
export default data;
